In [3]:
import numpy as np

A = np.arange(1,10).reshape(3,3)

print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
B = np.random.random((3,4))

print(B)

[[0.06201626 0.0826367  0.15395211 0.00665339]
 [0.69512862 0.19917374 0.57909576 0.39435043]
 [0.42739963 0.93017667 0.95985524 0.38402368]]


In [10]:
C = np.diag([1,2,3])

print(C)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [12]:
D = np.identity(4, dtype = np.float32 )

print(D)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [21]:
test1 = np.matrix([[4,1],[1,1]])
test2 = np.matrix([[1,17],[1,9]])

print( test1 * test2 )
print( test1 @ test2 )

[[ 5 77]
 [ 2 26]]
[[ 5 77]
 [ 2 26]]


In [26]:
E = np.triu([[1,2,3], [2,3,4], [4,5,6]], k = 0)

print(E)

[[1 2 3]
 [0 3 4]
 [0 0 6]]


In [43]:
F = np.tril([[1,2,3], [2,3,4], [4,5,6]], k = 0)

print(F)

[[1 0 0]
 [2 3 0]
 [4 5 6]]


In [38]:
import numpy.linalg as la

print(int (la.det(F)))
la.inv(F)

array([[ 1.00000000e+00, -5.55111512e-17,  0.00000000e+00],
       [-6.66666667e-01,  3.33333333e-01, -0.00000000e+00],
       [-1.11111111e-01, -2.77777778e-01,  1.66666667e-01]])