In [1]:
import numpy as np 

In [6]:
A = np.array([[1,2,3],[4,5,6]])
print(A)
print(A[1])
print(A[1][2])

[[1 2 3]
 [4 5 6]]
[4 5 6]
6


In [41]:
seed = 

B = np.random.RandomState(seed).randint(10,25, size=6).reshape(2,3) # 2 by 3 matrix

print(B)

[[24 23 24]
 [12 22 12]]


In [44]:
C = np.matrix([[1,2], [3,4], [5,6]])

print(C)

[[1 2]
 [3 4]
 [5 6]]


In [57]:
D = np.zeros( shape = (3, 3), dtype = np.int8 ) # 3 by 3 zero Matrix, data type : 8 bit int

print(D) 

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [47]:
E = np.ones(shape = (3, 3)) # 3 by 3 basic matrix, data type : 64 bit float

print(E)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [60]:
F = np.identity(5 ,dtype = np.int64 ) # 5 by 5 identity matrix, data type : 64 bit int

print(F)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [68]:
U = np.eye( 3, 5, dtype = np.float64 )# 3 by 5 matrix, data type : 64 bit float

print(U)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [71]:
print( A @ C ) # Matrix multiplication Operator : "@"
print( A * C ) # Matrix multiplication Operator : "*"

[[22 28]
 [49 64]]


In [72]:
print( np.matmul(A,C) ) # Matrix multiplication Function : np.matmul(,)

[[22 28]
 [49 64]]


In [73]:
print( A.T ) #Transposition Matrix Operator : ".T"

array([[1, 4],
       [2, 5],
       [3, 6]])

In [78]:
print( (A.T).T ) # A = (A.T).T
print( (A @ C).T ) # (A @ C ).T = B.T * A.T

[[1 2 3]
 [4 5 6]]
[[22 49]
 [28 64]]
